# Generated by Django 3.0.5 on 2022-06-09 11:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campania',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('codigo_interno', models.CharField(max_length=20)),
                ('descripcion', models.TextField(blank=True, max_length=500, null=True)),
                ('titulo', models.CharField(max_length=350)),
                ('objetivos_principales', models.TextField(blank=True, max_length=5000, null=True)),
                ('objetivos_secundarios', models.TextField(blank=True, max_length=5000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoginMIC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.TextField(blank=True, max_length=70, null=True)),
                ('campania_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Muestreador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
                ('observaciones', models.CharField(blank=True, max_length=150, null=True)),
                ('codigo', models.CharField(max_length=10)),
                ('muestra', models.BooleanField(default=False)),
                ('continuo', models.BooleanField(default=False)),
                ('generico', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('iso', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=15, null=True)),
                ('descripcion', models.TextField(max_length=140, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Puerto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('lat', models.FloatField(null=True)),
                ('lon', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoMuestreador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('descripcion', models.CharField(max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='TipoObjetivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=6, null=True)),
                ('descripcion', models.TextField(max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='TipoPlataforma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=140)),
                ('codigo_ICES', models.CharField(max_length=6, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campania', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campanias.Campania')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Plataforma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_ICES', models.CharField(max_length=4)),
                ('codigo_bardo', models.CharField(max_length=35, null=True)),
                ('nombre', models.CharField(max_length=30)),
                ('matricula', models.CharField(max_length=7, null=True)),
                ('sradial', models.CharField(blank=True, max_length=7, null=True)),
                ('mat_sat', models.CharField(blank=True, max_length=7, null=True)),
                ('descripcion', models.CharField(max_length=250, null=True)),
                ('pais', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='campanias.Pais')),
                ('tipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='campanias.TipoPlataforma')),
            ],
        ),
        migrations.CreateModel(
            name='Parametro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=6)),
                ('codigo_ICES', models.CharField(max_length=6, null=True)),
                ('codigo_ISO', models.CharField(max_length=6, null=True)),
                ('descripcion', models.TextField(max_length=140)),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='campanias.Parametro')),
            ],
        ),
        migrations.CreateModel(
            name='MuestreadorABordo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacion', models.TextField(blank=True, max_length=1500, null=True)),
                ('asignado', models.BooleanField(default=False)),
                ('marca', models.CharField(blank=True, max_length=100, null=True)),
                ('modelo', models.CharField(blank=True, max_length=100, null=True)),
                ('calibracion', models.DateField(blank=True, null=True)),
                ('campania', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='muestreadores', to='campanias.Campania')),
                ('laboratorio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='personas.Laboratorio')),
                ('muestreador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='muestreadore', to='campanias.Muestreador')),
            ],
        ),
        migrations.AddField(
            model_name='muestreador',
            name='parametros',
            field=models.ManyToManyField(to='campanias.Parametro'),
        ),
        migrations.AddField(
            model_name='muestreador',
            name='tipo_muestreador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='muestreador', to='campanias.TipoMuestreador'),
        ),
        migrations.CreateModel(
            name='Integrantes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campania', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrantes', to='campanias.Campania')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.Persona')),
                ('rol', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='personas.RolPersona')),
            ],
        ),
        migrations.CreateModel(
            name='EtiquetaObjetivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=6)),
                ('descripcion', models.TextField(max_length=140)),
                ('tipo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='campanias.TipoObjetivo')),
            ],
        ),
        migrations.CreateModel(
            name='Etapa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('fecha_init', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('campania', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapas', to='campanias.Campania')),
                ('puerto_destino', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pto_destino', to='campanias.Puerto')),
                ('puerto_origen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pto_origen', to='campanias.Puerto')),
            ],
        ),
        migrations.CreateModel(
            name='Estrato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('area', models.FloatField()),
                ('cuadricula', models.IntegerField()),
                ('zona', models.TextField(max_length=340, null=True)),
                ('campania', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estratos', to='campanias.Campania')),
            ],
        ),
        migrations.AddField(
            model_name='campania',
            name='objetivos_etiqueta',
            field=models.ManyToManyField(to='campanias.EtiquetaObjetivo'),
        ),
        migrations.AddField(
            model_name='campania',
            name='plataforma',
            field=models.ManyToManyField(related_name='plataforma', to='campanias.Plataforma'),
        ),
        migrations.AddField(
            model_name='campania',
            name='programa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='campanias.Programa'),
        ),
    ]
