# Generated by Django 3.0.5 on 2022-06-09 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campanias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EspacioTemporal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(blank=True, null=True)),
                ('lat', models.FloatField(null=True)),
                ('lon', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EstacionGeneral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_plan', models.IntegerField(null=True)),
                ('nro_transecta', models.CharField(blank=True, max_length=10, null=True)),
                ('nro_estacion_barco', models.IntegerField(blank=True, null=True)),
                ('espacio_tiempo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='estaciones.EspacioTemporal')),
                ('estrato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estratos', to='campanias.Estrato')),
                ('etapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estaciones', to='campanias.Etapa')),
            ],
        ),
        migrations.CreateModel(
            name='Operacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exitosa', models.BooleanField(default=True)),
                ('observaciones', models.TextField(blank=True, max_length=1500, null=True)),
                ('confirmado', models.BooleanField(default=False)),
                ('estacion_general', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operaciones', to='estaciones.EstacionGeneral')),
                ('fin_espacio_temporal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='espacio_final', to='estaciones.EspacioTemporal')),
                ('inicio_espacio_temporal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='espacio_inicial', to='estaciones.EspacioTemporal')),
                ('muestreador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campanias.MuestreadorABordo')),
            ],
        ),
        migrations.CreateModel(
            name='ParametroPorOp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parametros', to='estaciones.Operacion')),
                ('parametro', models.ManyToManyField(related_name='para', to='campanias.Parametro')),
            ],
        ),
        migrations.CreateModel(
            name='DatoAmbiental',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presion', models.FloatField(blank=True, null=True)),
                ('viento_dir', models.IntegerField(blank=True, null=True)),
                ('viento', models.IntegerField(blank=True, null=True)),
                ('temperatura_bs', models.FloatField(blank=True, null=True)),
                ('temperatura_bh', models.FloatField(blank=True, null=True)),
                ('nubes_cant', models.IntegerField(blank=True, null=True)),
                ('nubes_tipo', models.IntegerField(blank=True, null=True)),
                ('visibilidad', models.IntegerField(blank=True, null=True)),
                ('mar_estado', models.IntegerField(blank=True, null=True)),
                ('mar_direccion', models.IntegerField(blank=True, null=True)),
                ('profundidad', models.FloatField(blank=True, null=True)),
                ('estacion_general', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dato_ambiental', to='estaciones.EstacionGeneral')),
            ],
        ),
    ]
